#!/usr/bin/php -q
<?php

require("classes/core.class.php");
require("classes/ircd.class.php");
$core = new core();
$ircd = new ircd();
$core->init('config.ini');
$core->debug("listening for new clients");
while(true){
    $un = NULL;
    //read-loop for new connections
    $reads = $core->_sockets;
    $writes = $reads;
    if(socket_select($reads, $writes, $un, 0) > 0){
    
    foreach($core->_sockets as $socket){
      while(in_array($socket, $reads)){
        if(count($core->_clients) >= $core->config['ircd']['maxusers']){
            $new = @socket_accept($socket);
            $core->write($new, "ERROR: Maximum clients reached. Please use a different server.");
            $ircd->quit($new,'Error: Server Full');
            continue;
        }
        $new = @socket_accept($socket);
        socket_set_nonblock($new);
        $core->sock_num++;
        $core->_client_sock[(int)$core->sock_num] = $new;
        socket_getpeername($new, $client['ip']);
        $client['lastping'] = time();
        $client['lastpong'] = $client['lastping'];
        $client['nick'] = NULL;
        $client['registered'] = FALSE;
        $client['regbit'] = 0;
        $core->write($new, ":".$core->config['me']['servername']." NOTICE AUTH :*** Looking up your hostname...");
        $core->debug("new client: {$client['ip']}");
        $hn = gethostbyaddr($client['ip']);
        if($hn == $client['ip']){
            $client['address'] = $client['ip'];
            $core->write($new, ":".$core->config['me']['servername']." NOTICE AUTH :*** Can't resolve your hotsname, using your IP instead.");
        } else {
            $client['address'] = $hn;
            $core->write($new, ":".$core->servname." NOTICE AUTH :*** Found your hostname.");
        }
        $core->_clients[(int)$core->sock_num] = $client;
        unset($reads[array_search($socket, $reads)]);
      }
    }
    }
    $reads = $writes = $core->_client_sock;
    if(@socket_select($reads, $writes, $un, 0) > 0){
      foreach($reads as $key => $value){
        if(false !== ($buf = $core->read($value))){
            $data = trim($buf);
            if(!empty($data)){
                if(strpos($data, "\n") >= 0 || strpos($data, "\r") >= 0){
                    $data = str_replace("\r","\n", $data);
                    $exp = explode("\n", $data);
                    $data = array();
                    foreach($exp as $d){
                        $d = trim($d);
                        if(!empty($d)){
                            $data[] = $d;
                        }
                    }
                }
                foreach($data as $work){
                    if($core->_clients[$key]['registered'] == TRUE){
                        $ircd->process($work, $key);
                    } else {
                        $ircd->newConnection($work, $key);
                    }
                }
            } else {
                $core->debug("Closing Link: client ".(empty($core->_clients[$key]['prefix'])?$core->_clients[$key]['address']:$core->_clients[$key]['prefix']).": Client Exited");
                unset($reads[$key]);
                $ircd->quit($key);
            }
        } else {
            $core->debug("Closing Link: client {$core->_clients[$key]['prefix']}: ".socket_strerror(socket_last_error($value)));
            unset($reads[$key]);
            $ircd->quit($key);
        }
    }//end while
    }//end if socket_select
    //do this every iteration regardless of socket state
    foreach($core->_clients as $key => $value){
        if((time() - $core->_clients[$key]['lastpong']) > $core->config['ircd']['pingfreq']){
            if(!$value['registered']){
                $core->write($core->_client_sock[$key],"ERROR: Closing link: ".$value['prefix']." (Ping timeout)");
                $core->debug("Closing Link: client {$value['prefix']} (Ping Timeout)");
                $ircd->quit($key);
            } else {
                if($core->_clients[$key]['lastping'] <= $core->_clients[$key]['lastpong']){
                    $ircd->ping($key, $core->servname, TRUE);
                    $core->_clients[$key]['lastping'] = time();
                }
            }
        }
        if(time() > ($core->_clients[$key]['lastpong'] + $core->config['ircd']['pingfreq'] + $core->config['ircd']['pingout'])){
            $core->write($core->_client_sock[$key],"ERROR: Closing link: ".$value['prefix']." (Ping timeout)");
            $core->debug("Closing Link: client {$value['address']} (Ping Timeout)");
            $ircd->quit($key);
        }
    }
        usleep(700);
}
foreach($core->_sockets as $socket)
    socket_close($socket);
?>
